const contexts = [
  "ArrowFunctionExpression",
  "FunctionDeclaration",
  "FunctionExpression",
  "TSCallSignatureDeclaration",
  "TSConstructSignatureDeclaration",
  "TSDeclareFunction",
  "TSFunctionType",
  "TSMethodSignature"
];

module.exports = {
  plugins: ["jsdoc"],
  rules: {
    // eslint-disable-next-line no-warning-comments
    // fixme: https://github.com/gajus/eslint-plugin-jsdoc/issues/857
    "jsdoc/check-access": ["warn", { contexts }],
    "jsdoc/check-alignment": ["warn", { contexts }],
    "jsdoc/check-examples": "off",
    "jsdoc/check-indentation": "warn",
    "jsdoc/check-line-alignment": "warn",
    "jsdoc/check-param-names": "warn",
    "jsdoc/check-property-names": "warn",
    "jsdoc/check-syntax": ["warn", { contexts }],
    "jsdoc/check-tag-names": ["warn", { definedTags: ["jest-environment"] }],
    "jsdoc/check-types": "warn",
    "jsdoc/check-values": "warn",
    "jsdoc/empty-tags": "warn",
    "jsdoc/implements-on-classes": ["warn", { contexts }],
    "jsdoc/match-description": ["warn", { contexts }],
    "jsdoc/match-name": "off",
    "jsdoc/multiline-blocks": ["warn", { contexts }],
    "jsdoc/newline-after-description": "warn",
    "jsdoc/no-bad-blocks": "warn",
    "jsdoc/no-defaults": ["warn", { contexts }],
    "jsdoc/no-missing-syntax": "off",
    "jsdoc/no-multi-asterisks": ["warn", { contexts }],
    "jsdoc/no-restricted-syntax": "off",
    "jsdoc/no-types": ["warn", { contexts }],
    "jsdoc/no-undefined-types": "warn",
    "jsdoc/require-asterisk-prefix": "warn",
    "jsdoc/require-description": ["warn", { contexts }],
    "jsdoc/require-description-complete-sentence": "warn",
    "jsdoc/require-example": "off",
    "jsdoc/require-file-overview": "off",
    "jsdoc/require-hyphen-before-param-description": "warn",
    "jsdoc/require-jsdoc": "off",
    "jsdoc/require-param": ["warn", { contexts }],
    "jsdoc/require-param-description": ["warn", { contexts }],
    "jsdoc/require-param-name": ["warn", { contexts }],
    "jsdoc/require-param-type": "off",
    "jsdoc/require-property": ["warn", { contexts }],
    "jsdoc/require-property-description": ["warn", { contexts }],
    "jsdoc/require-property-name": ["warn", { contexts }],
    "jsdoc/require-property-type": ["warn", { contexts }],
    "jsdoc/require-returns": ["warn", { checkGetters: false, contexts }],
    "jsdoc/require-returns-check": "warn",
    "jsdoc/require-returns-description": ["warn", { contexts }],
    "jsdoc/require-returns-type": "off",
    "jsdoc/require-throws": "off",
    "jsdoc/require-yields": "off",
    "jsdoc/require-yields-check": ["warn", { contexts }],
    "jsdoc/sort-tags": ["warn", { contexts }],
    "jsdoc/tag-lines": "warn",
    "jsdoc/valid-types": ["warn", { contexts }]
  }
};
