<?php

$phpCsRules = [
  '@Symfony' => true,
  'align_multiline_comment' => ['comment_type' => 'all_multiline'],
  'array_indentation' => true,
  'array_syntax' => ['syntax' => 'short'],
  'backtick_to_shell_exec' => true,
  'binary_operator_spaces' => ['default' => 'single_space'],
  'blank_line_after_namespace' => true,
  'blank_line_after_opening_tag' => true,
  'blank_line_before_statement' => [
    'statements' => ['case', 'default', 'return']
  ],
  'braces' => [
    'allow_single_line_closure' => true,
    'position_after_anonymous_constructs' => 'same',
    'position_after_control_structures' => 'same',
    'position_after_functions_and_oop_constructs' => 'same'
  ],
  'cast_spaces' => ['space' => 'single'],
  'class_attributes_separation' => [
    'elements' => ['const', 'method', 'property']
  ],
  'class_definition' => [
    'multi_line_extends_each_single_line' => true,
    'single_item_single_line' => true,
    'single_line' => true
  ],
  'class_keyword_remove' => false,
  'clean_namespace' => true,
  'combine_consecutive_issets' => true,
  'combine_consecutive_unsets' => true,
  'compact_nullable_typehint' => true,
  'concat_space' => ['spacing' => 'none'],
  'constant_case' => ['case' => 'lower'],
  'declare_equal_normalize' => ['space' => 'none'],
  'doctrine_annotation_array_assignment' => [],
  'doctrine_annotation_braces' => true,
  'doctrine_annotation_indentation' => [],
  'doctrine_annotation_spaces' => [],
  'echo_tag_syntax' => true,
  'elseif' => true,
  'encoding' => true,
  'escape_implicit_backslashes' => [
    'double_quoted' => true,
    'heredoc_syntax' => true,
    'single_quoted' => true
  ],
  'explicit_indirect_variable' => true,
  'explicit_string_variable' => true,
  'full_opening_tag' => true,
  'fully_qualified_strict_types' => true,
  'function_declaration' => ['closure_function_spacing' => 'one'],
  'function_typehint_space' => true,
  'general_phpdoc_annotation_remove' => true,
  'general_phpdoc_tag_rename' => true,
  'global_namespace_import' => [
    'import_classes' => true,
    'import_constants' => true,
    'import_functions' => true
  ],
  'heredoc_indentation' => true,
  'heredoc_to_nowdoc' => true,
  'include' => true,
  'increment_style' => ['style' => 'pre'],
  'indentation_type' => true,
  'lambda_not_used_import' => true,
  'line_ending' => true,
  'linebreak_after_opening_tag' => true,
  'list_syntax' => ['syntax' => 'short'],
  'lowercase_cast' => true,
  'lowercase_keywords' => true,
  'lowercase_static_reference' => true,
  'magic_constant_casing' => true,
  'magic_method_casing' => true,
  'method_argument_space' => true,
  'method_chaining_indentation' => true,
  'multiline_comment_opening_closing' => true,
  'multiline_whitespace_before_semicolons' => true,
  'native_function_casing' => true,
  'native_function_type_declaration_casing' => true,
  'new_with_braces' => true,
  'no_alias_language_construct_call' => true,
  'no_alternative_syntax' => true,
  'no_binary_string' => true,
  'no_blank_lines_after_class_opening' => true,
  'no_blank_lines_after_phpdoc' => true,
  'no_blank_lines_before_namespace' => false,
  'no_break_comment' => ['comment_text' => 'no break'],
  'no_closing_tag' => true,
  'no_empty_comment' => true,
  'no_empty_phpdoc' => true,
  'no_empty_statement' => true,
  'no_extra_blank_lines' => [
    'tokens' => [
      'break',
      'case',
      'continue',
      'curly_brace_block',
      'default',
      'extra',
      'parenthesis_brace_block',
      'return',
      'square_brace_block',
      'switch',
      'throw',
      'use',
      'use_trait'
    ]
  ],
  'no_leading_import_slash' => true,
  'no_leading_namespace_whitespace' => true,
  'no_mixed_echo_print' => ['use' => 'echo'],
  'no_multiline_whitespace_around_double_arrow' => true,
  'no_null_property_initialization' => true,
  'no_short_bool_cast' => true,
  'no_singleline_whitespace_before_semicolons' => true,
  'no_spaces_after_function_name' => true,
  'no_spaces_around_offset' => [
    'positions' => ['inside', 'outside']
  ],
  'no_spaces_inside_parenthesis' => true,
  'no_superfluous_elseif' => true,
  'no_superfluous_phpdoc_tags' => [
    'allow_mixed' => false,
    'allow_unused_params' => false,
    'remove_inheritdoc' => true
  ],
  'no_trailing_comma_in_list_call' => true,
  'no_trailing_comma_in_singleline_array' => true,
  'no_trailing_whitespace' => true,
  'no_trailing_whitespace_in_comment' => true,
  'no_unneeded_control_parentheses' => [
    'statements' => [
      'break',
      'clone',
      'continue',
      'echo_print',
      'return',
      'switch_case',
      'yield'
    ]
  ],
  'no_unneeded_curly_braces' => true,
  'no_unset_cast' => true,
  'no_unused_imports' => true,
  'no_useless_else' => true,
  'no_useless_return' => true,
  'no_whitespace_before_comma_in_array' => true,
  'no_whitespace_in_blank_line' => true,
  'normalize_index_brace' => true,
  'not_operator_with_space' => false,
  'not_operator_with_successor_space' => false,
  'nullable_type_declaration_for_default_null_value' => [
    'use_nullable_type_declaration' => false
  ],
  'object_operator_without_whitespace' => true,
  'operator_linebreak' => null,
  'ordered_class_elements' => [
    'use_trait',
    'constant_public',
    'property_public',
    'construct',
    'destruct',
    'magic',
    'phpunit',
    'method_public',
    'constant_protected',
    'property_protected',
    'method_protected',
    'constant_private',
    'property_private',
    'method_private'
  ],
  'ordered_imports' => ['sort_algorithm' => 'alpha'],
  'php_unit_fqcn_annotation' => true,
  'php_unit_internal_class' => null,
  'php_unit_method_casing' => ['case' => 'camel_case'],
  'php_unit_size_class' => null,
  'php_unit_test_class_requires_covers' => null,
  'phpdoc_add_missing_param_annotation' => true,
  'phpdoc_align' => ['align' => 'vertical'],
  'phpdoc_annotation_without_dot' => true,
  'phpdoc_indent' => true,
  'phpdoc_inline_tag_normalizer' => true,
  'phpdoc_line_span' => ['const' => 'multi'],
  'phpdoc_no_access' => true,
  'phpdoc_no_alias_tag' => true,
  'phpdoc_no_empty_return' => true,
  'phpdoc_no_package' => true,
  'phpdoc_no_useless_inheritdoc' => true,
  'phpdoc_order' => true,
  'phpdoc_order_by_value' => true,
  'phpdoc_return_self_reference' => [],
  'phpdoc_scalar' => [],
  'phpdoc_separation' => true,
  'phpdoc_single_line_var_spacing' => true,
  'phpdoc_summary' => false,
  'phpdoc_tag_casing' => true,
  'phpdoc_tag_type' => true,
  'phpdoc_to_comment' => true,
  'phpdoc_trim' => true,
  'phpdoc_trim_consecutive_blank_line_separation' => true,
  'phpdoc_types' => [
    'groups' => [
      'simple',
      'alias',
      'meta'
    ]
  ],
  'phpdoc_types_order' => [
    'null_adjustment' => 'always_first',
    'sort_algorithm' => 'alpha'
  ],
  'phpdoc_var_annotation_correct_order' => true,
  'phpdoc_var_without_name' => true,
  'protected_to_private' => true,
  'return_assignment' => true,
  'return_type_declaration' => ['space_before' => 'none'],
  'self_static_accessor' => true,
  'semicolon_after_instruction' => true,
  'short_scalar_cast' => true,
  'simple_to_complex_string_variable' => true,
  'simplified_if_return' => true,
  'simplified_null_return' => true,
  'single_blank_line_at_eof' => true,
  'single_blank_line_before_namespace' => true,
  'single_class_element_per_statement' => true,
  'single_import_per_statement' => true,
  'single_line_after_imports' => true,
  'single_line_comment_style' => true,
  'single_line_throw' => true,
  'single_quote' => ['strings_containing_single_quote_chars' => true],
  'single_space_after_construct' => true,
  'single_trait_insert_per_statement' => true,
  'space_after_semicolon' => true,
  'standardize_increment' => true,
  'standardize_not_equals' => true,
  'switch_case_semicolon_to_colon' => true,
  'switch_case_space' => true,
  'switch_continue_to_break' => true,
  'ternary_operator_spaces' => true,
  'ternary_to_null_coalescing' => true,
  'trailing_comma_in_multiline_array' => false,
  'trim_array_spaces' => true,
  'unary_operator_spaces' => true,
  'visibility_required' => [],
  'whitespace_after_comma_in_array' => true,
  'yoda_style' => false
];
