module.exports = {
  plugins: ["stylelint-scss"],
  rules: {
    "scss/at-each-key-value-single-line": true,
    "scss/at-else-closing-brace-newline-after": "always-last-in-chain",
    "scss/at-else-closing-brace-space-after": "never-intermediate",
    "scss/at-else-empty-line-before": "never",
    "scss/at-else-if-parentheses-space-before": "always",
    "scss/at-extend-no-missing-placeholder": true,
    "scss/at-function-named-arguments": undefined,
    "scss/at-function-parentheses-space-before": "always",
    "scss/at-function-pattern": "always",
    "scss/at-if-closing-brace-newline-after": "always-last-in-chain",
    "scss/at-if-closing-brace-space-after": "always-intermediate",
    "scss/at-if-no-null": true,
    "scss/at-import-no-partial-leading-underscore": true,
    "scss/at-import-partial-extension": undefined,
    "scss/at-import-partial-extension-blacklist": undefined,
    "scss/at-import-partial-extension-whitelist": undefined,
    "scss/at-mixin-argumentless-call-parentheses": "always",
    "scss/at-mixin-named-arguments": "always",
    "scss/at-mixin-parentheses-space-before": "always",
    "scss/at-mixin-pattern": "always",
    "scss/at-rule-conditional-no-parentheses": true,
    "scss/at-rule-no-unknown": true,
    "scss/comment-no-empty": true,
    "scss/comment-no-loud": undefined,
    "scss/declaration-nested-properties": "never",
    "scss/declaration-nested-properties-no-divided-groups": true,
    "scss/dimension-no-non-numeric-values": true,
    "scss/dollar-variable-colon-newline-after": "always-multi-line",
    "scss/dollar-variable-colon-space-after": "always",
    "scss/dollar-variable-colon-space-before": "always",
    "scss/dollar-variable-default": true,
    "scss/dollar-variable-empty-line-after": [
      "always",
      { except: ["before-dollar-variable", "last-nested"] }
    ],
    "scss/dollar-variable-empty-line-before": [
      "always",
      { except: ["after-dollar-variable", "first-nested"] }
    ],
    "scss/dollar-variable-first-in-block": [
      true,
      { ignore: ["comments", "imports"] }
    ],
    "scss/dollar-variable-no-missing-interpolation": true,
    "scss/dollar-variable-pattern": undefined,
    "scss/double-slash-comment-empty-line-before": "always",
    "scss/double-slash-comment-inline": "always",
    "scss/double-slash-comment-whitespace-inside": "always",
    "scss/function-color-relative": true,
    "scss/function-quote-no-quoted-strings-inside": true,
    "scss/function-unquote-no-unquoted-strings-inside": true,
    "scss/map-keys-quotes": "always",
    "scss/media-feature-value-dollar-variable": "always",
    "scss/no-dollar-variables": undefined,
    "scss/no-duplicate-dollar-variables": true,
    "scss/no-duplicate-mixins": true,
    "scss/no-global-function-names": true,
    "scss/operator-no-newline-after": true,
    "scss/operator-no-newline-before": true,
    "scss/operator-no-unspaced": true,
    "scss/partial-no-import": true,
    "scss/percent-placeholder-pattern": "always",
    "scss/selector-nest-combinators": undefined,
    "scss/selector-no-redundant-nesting-selector": true,
    "scss/selector-no-union-class-name": true
  }
};
